[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.11.0"
diesel = { version = "2.1.0", features = ["sqlite"] }
dotenvy = "0.15"
